# Mica config

use_pretrained: False

dataset:
  root: '/mnt/disks/data/datasets'
  training_data: [ 'VHTRAIN' ]
  eval_data: [ 'VHVALID' ]
  num_workers: 4
  batch_size: 8
  K: 2
  use_shape_params: False

train:
  lr: 1e-5
  arcface_lr: 1e-5
  weight_decay: 2e-4
  max_shape_code: 3.
  fresh: True
  reset_optimizer: False
  max_steps: 160000
  log_steps: 50
  val_steps: 300
  vis_steps: 1200
  val_save_img: 1200
  checkpoint_steps: 1000
  checkpoint_epochs_steps: 10000

model:
  arcface_unfreeze: 2
  arcface_use_pretrained: True
  n_shape: 300
  name: 'mica'
