# Mica config

use_pretrained: False

dataset:
  root: '/mnt/disks/data/datasets'
  training_data: [ 'VHTRAIN', 'MHTRAIN' ]   # Names of dataset and numpy image path file
  eval_data: [ 'VHVALID', 'MHVALID' ]
  num_workers: 4
  batch_size: 8
  K: 4                                      # Number of images used per subject
  use_shape_params: False
  random_flip: False
  random_flip_prob: 0.5
  add_noise: False
  add_noise_std: 0.1

train:
  lr: 1e-5
  arcface_lr: 1e-5
  weight_decay: 2e-4
  max_shape_code: 3.5                       # Maximum allowed absolute shape paramater
  norm: 2                                   # Norm value for distance calculations
  fresh: True                               # Whether to train a fresh model (overwrite existing)
  reset_optimizer: False
  max_steps: 30000
  log_steps: 50
  val_steps: 200
  vis_steps: 1000
  val_save_img: 1000
  checkpoint_steps: 1000                    # Overwrite model.tar
  checkpoint_epochs_steps: 10000            # Save a new tar file (model_10000.tar etc.)
  loss_keys: ['pred_chamfer_distance', 'penalty_shape_code'] # Metrics to use as loss

model:
  arcface_unfreeze: 0                       # Number Arcface layers to unfreeze
  arcface_use_pretrained: True
  mapping_layers: 3
  hidden_layers_size: 300
  n_shape: 300
  name: 'mica'

mask_weights:
  face: 150.
  ears: 1.
  eyes: 1e-6